version: '3.8'

services:
  nginx:
    image: photique/nginx-dev:0.1.0
    container_name: nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/html:/usr/share/nginx/html

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "certbot certonly --nginx -d www.photique.shop"