version: '3.8'

services:
  nginx:
    image: photique/nginx-dev:0.1.0
    container_name: nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /home/ubuntu/react:/home/ubuntu/react
    restart: always
    networks:
      - backend
    
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-dev
    command: certonly --webroot --webroot-path=/var/www/certbot --email photique0538@gmail.com --agree-tos --no-eff-email -d www.photique.shop --force-renewal
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /var/log/letsencrypt:/var/log/letsencrypt

networks:
  backend:
    name: backend
    driver: bridge