version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/photique0538/nginx/log:/var/log/nginx
      - /home/photique0538/nginx/conf.d:/etc/nginx/conf.d
      - /home/photique0538/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /home/photique0538/react:/home/ubuntu/react
    restart: always
    networks:
      - backend
    
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-prod
    command: certonly --webroot --webroot-path=/var/www/certbot --email photique0538@gmail.com --agree-tos --no-eff-email -d www.photique.site --force-renewal
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /var/log/letsencrypt:/var/log/letsencrypt

networks:
  backend:
    name: backend
    driver: bridge

