FROM nginx:latest

RUN apt-get update && apt-get install -y certbot python3-certbot-nginx && apt-get clean
RUN certbot certonly --nginx -d www.photique.shop
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443