name: 프로덕트 서버 Nginx 배포

on:
  pull_request:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 소스코드 체크아웃
      uses: actions/checkout@v3

    - name: EC2에 파일 복사
      uses: appleboy/scp-action@master
      with:
        username: photique0538
        host: ${{ secrets.HOST_PROD }}
        key: ${{ secrets.KEY_PROD }}
        script: |
          mkdir -p /home/photique0538/nginx/conf.d
          touch /home/photique0538/nginx/conf.d/default.conf
        source: docker/docker-compose.nginx.prod.yml, config/renew.prod.sh, config/nginx.blue.prod.conf, config/nginx.green.prod.conf, config/nginx.default.prod.conf, config/nginx.conf
        target: /home/photique0538/nginx

    - name: EC2 연결 및 도커컴포즈 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: photique0538
        key: ${{ secrets.KEY_PROD }}
        script: |
            mv /home/photique0538/nginx/docker/docker-compose.nginx.prod.yml /home/photique0538/nginx/
            mv /home/photique0538/nginx/config/*.conf /home/photique0538/nginx/
            mv /home/photique0538/nginx/config/*.sh /home/photique0538/nginx/
            rm -rf /home/photique0538/nginx/docker
            rm -rf /home/photique0538/nginx/config
            sudo cp /home/photique0538/nginx/nginx.default.prod.conf /home/photique0538/nginx/conf.d/default.conf
            docker-compose -f /home/photique0538/nginx/docker-compose.nginx.prod.yml down
            docker-compose -f /home/photique0538/nginx/docker-compose.nginx.prod.yml pull
            docker-compose -f /home/photique0538/nginx/docker-compose.nginx.prod.yml up -d
            docker image prune -a -f
            docker exec -i nginx-prod nginx -s reload

    - name: EC2 연결 및 ssl 인증서 갱신 크론탭 설정
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: photique0538
        key: ${{ secrets.KEY_PROD }}
        script: |
            chmod +x /home/photique0538/nginx/renew.prod.sh
            (crontab -l 2>/dev/null; echo "0 0 1 */2 * /home/photique0538/nginx/renew.prod.sh >> /var/log/renew.log 2>&1") | crontab -
            crontab -l
