name: 개발서버 Nginx 배포

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 소스코드 체크아웃
      uses: actions/checkout@v3

    - name: EC2에 파일 복사
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST_DEV }}
        key: ${{ secrets.KEY }}
        script: mkdir -p /home/ubuntu/nginx
        source: ./docker/docker-compose.nginx.dev.yml, ./config/renew.dev.sh, ./config/nginx.blue.dev.conf, ./config/nginx.green.dev.conf, ./config/nginx.default.dev.conf, ./config/nginx.conf
        target: /home/ubuntu/nginx

    - name: EC2 연결 및 도커컴포즈 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            docker-compose -f /home/ubuntu/nginx/docker-compose.nginx.dev.yml down
            docker-compose -f /home/ubuntu/nginx/docker-compose.nginx.dev.yml pull
            docker-compose -f /home/ubuntu/nginx/docker-compose.nginx.dev.yml up -d
            docker image prune -a -f
            sudo cp /home/ubuntu/nginx/nginx.default.dev.conf /home/ubuntu/nginx/conf.d/default.conf
            docker exec -i nginx-dev nginx -s reload

    - name: EC2 연결 및 ssl 인증서 갱신 크론탭 설정
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            chmod +x /home/ubuntu/nginx/renew.dev.sh
            (crontab -l 2>/dev/null; echo "0 0 1 */2 * /home/ubuntu/nginx/renew.dev.sh >> /var/log/renew.log 2>&1") | crontab -
            crontab -l
