name: 개발서버 Nginx 배포

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 소스코드 체크아웃
      uses: actions/checkout@v3

    -name: tar를 위한 권한부여
      run: chmod -R +w ./nginx

    - name: Nginx 도커 이미지 빌드 및 푸시
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -f ./nginx/Dockerfile.dev -t ${{ secrets.DOCKER_REPO_DEV }}:0.1.0 ./nginx
        docker push ${{ secrets.DOCKER_REPO_DEV }}:0.1.0

    - name: EC2에 파일 복사
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST_DEV }}
        key: ${{ secrets.KEY }}
        source: ./docker-compose.nginx.dev.yml, ./renew.sh, ./nginx/nginx.blue.dev.conf, ./nginx/nginx.green.dev.conf
        target: /home/ubuntu

    - name: EC2 연결 및 도커컴포즈 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            sudo docker-compose -f docker-compose.nginx.dev.yml down
            sudo docker-compose -f docker-compose.nginx.dev.yml pull
            sudo docker-compose -f docker-compose.nginx.dev.yml up -d
            sudo docker image prune -a -f

    - name: EC2 연결 및 ssl 인증서 갱신 크론탭 설정
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            chmod +x /home/ubuntu/renew.sh
            (crontab -l 2>/dev/null; echo "0 0 1 */2 * /home/ubuntu/renew.sh >> /var/log/renew.log 2>&1") | crontab -
            crontab -l
