name: 개발서버 Nginx 배포

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 소스코드 체크아웃
      uses: actions/checkout@v3

    - name: Nginx 도커 이미지 빌드 및 푸시
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -f ./nginx/Dockerfile.dev -t ${{ DOCKER_REPO_DEV }}:0.1.0 ./nginx
        docker push ${{ secrets.DOCKER_REPO_DEV }}:0.1.0
        // 레포이름을 nginx/dev로해야함


    - name: EC2에 파일 복사
      run: |
        scp -i ${{ secrets.KEY }} ./docker-compose.nginx.dev.yml ${{ secrets.HOST_DEV }}:/home/ubuntu/docker-compose.nginx.dev.yml

    - name: EC2 연결 및 도커컴포즈 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            docker-compose -f docker-compose.yml down --remove-orphans
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
            docker image prune -a -f
