name: 개발서버 Nginx 배포

on:
  push:
    branches:
      - develop

jobs:
  개발서버 패포:
    runs-on: ubuntu-latest

    steps:
    - name: 소스코드 체크아웃
      uses: actions/checkout@v3

    - name: 도커 로그인
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Nginx Docker 이미지 빌드
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dev/nginx:0.1.0 -f ./nginx/Dockerfile.dev ./nginx

    - name: Docker Hub에 이미지 푸시
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dev/nginx:0.1.0

    - name: EC2에 파일 복사
      run: |
        scp -i ${{ secrets.KEY }} ./docker-compose.nginx.dev.yml ${{ secrets.HOST_DEV }}:/home/ubuntu/docker-compose.nginx.dev.yml

    - name: EC2 연결 및 도커컴포즈 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
            docker-compose -f docker-compose.yml down --remove-orphans
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
            docker image prune -a -f
